// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkutfdrercvwuhoafdna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrdXRmZHJlcmN2d3Vob2FmZG5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTEyNzYsImV4cCI6MjA1OTY2NzI3Nn0.eUaplBJ-NiVh4eFVfvSFSkbIm-eCoZeu-x7LIYmcipQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);